"""
update.py — ZxZone-MLBX deployment helper for Heroku.

MINIMUM required Heroku config vars (only these 2 are truly mandatory):
  BOT_TOKEN     — identifies which MongoDB partition to load
  DATABASE_URL  — MongoDB connection string

Everything else (UPSTREAM_REPO, UPSTREAM_BRANCH, TELEGRAM_API, TELEGRAM_HASH,
OWNER_ID, etc.) is loaded from MongoDB automatically.
You only need them in Heroku config vars for the VERY FIRST boot.
After that they persist in MongoDB and can be removed from Heroku.
"""

from logging import ERROR, INFO, FileHandler, StreamHandler, basicConfig, getLogger
from os import environ, path
from subprocess import call as scall
from subprocess import run as srun
from sys import exit

from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi

getLogger("pymongo").setLevel(ERROR)

basicConfig(
    format="[%(asctime)s] [%(levelname)s] - %(message)s",
    datefmt="%d-%b-%y %I:%M:%S %p",
    handlers=[FileHandler("log.txt"), StreamHandler()],
    level=INFO,
)
_LOGGER = getLogger("update")

# ── Step 1: BOT_TOKEN ───────────────────────────────────────────────────────
BOT_TOKEN = environ.get("BOT_TOKEN", "").strip()
if not BOT_TOKEN:
    if path.exists("config.env"):
        for line in open("config.env"):
            line = line.strip()
            if line.startswith("BOT_TOKEN="):
                BOT_TOKEN = line[len("BOT_TOKEN="):].strip().strip('"').strip("'")
                break
if not BOT_TOKEN:
    _LOGGER.error("BOT_TOKEN is missing! Set it in Heroku config vars. Exiting.")
    exit(1)

BOT_ID = BOT_TOKEN.split(":", 1)[0]
DATABASE_URL = environ.get("DATABASE_URL", "").strip()

if not DATABASE_URL and path.exists("config.env"):
    for line in open("config.env"):
        line = line.strip()
        if line.startswith("DATABASE_URL="):
            DATABASE_URL = line[len("DATABASE_URL="):].strip().strip('"').strip("'")
            break

# ── Step 2: Load config from MongoDB ────────────────────────────────────────
UPSTREAM_REPO   = environ.get("UPSTREAM_REPO", "").strip()
UPSTREAM_BRANCH = environ.get("UPSTREAM_BRANCH", "").strip()
UPDATE_PKGS     = environ.get("UPDATE_PKGS", "True").strip()
db_doc = None

if DATABASE_URL:
    try:
        conn = MongoClient(DATABASE_URL, server_api=ServerApi("1"), serverSelectionTimeoutMS=8000)
        db   = conn.zxzone_mlbx
        db_doc = db.settings.config.find_one({"_id": BOT_ID})
        if db_doc:
            loaded = 0
            for key, value in db_doc.items():
                if key == "_id" or value is None:
                    continue
                if not environ.get(key):
                    environ[key] = str(value).strip()
                    loaded += 1
            _LOGGER.info(f"MongoDB: loaded {loaded} config var(s) into environ.")
            UPSTREAM_REPO   = environ.get("UPSTREAM_REPO", UPSTREAM_REPO).strip()
            UPSTREAM_BRANCH = environ.get("UPSTREAM_BRANCH", UPSTREAM_BRANCH).strip()
            UPDATE_PKGS     = environ.get("UPDATE_PKGS", UPDATE_PKGS).strip()
        conn.close()
    except Exception as e:
        _LOGGER.warning(f"MongoDB: could not load config — {e}")
else:
    _LOGGER.warning("DATABASE_URL not set — skipping MongoDB load.")

UPSTREAM_BRANCH = UPSTREAM_BRANCH or "main"

# ── Step 3: git reset ───────────────────────────────────────────────────────
if UPSTREAM_REPO:
    if path.exists(".git"):
        srun(["rm", "-rf", ".git"])

    update = srun(
        f"git init -q "
        f"&& git config --global user.email bot@zxzone-mlbx.local "
        f"&& git config --global user.name ZxZoneMLBX "
        f"&& git add . "
        f"&& git commit -sm update -q "
        f"&& git remote add origin {UPSTREAM_REPO} "
        f"&& git fetch origin -q "
        f"&& git reset --hard origin/{UPSTREAM_BRANCH} -q",
        shell=True,
    )
    
    if update.returncode == 0:
        _LOGGER.info("Successfully updated with Latest Updates !")
    else:
        _LOGGER.error("Git update failed! Check UPSTREAM_REPO/UPSTREAM_BRANCH.")
else:
    _LOGGER.warning("UPSTREAM_REPO not set — skipping git update.")

# ── Step 4: Write config.env ────────────────────────────────────────────────
_SKIP_KEYS = {"_id", "_____REMOVE_THIS_LINE_____"}

if db_doc:
    lines = [
        "# Auto-generated by update.py from MongoDB — do not edit manually.",
        "",
    ]
    written = 0
    for key, value in db_doc.items():
        if key in _SKIP_KEYS or value is None:
            continue
        str_val = str(value).strip()
        if str_val in ("", "None"):
            continue
        str_val_esc = str_val.replace('"', '\\"')
        lines.append(f'{key}="{str_val_esc}"')
        written += 1
    try:
        with open("config.env", "w") as f:
            f.write("\n".join(lines) + "\n")
        _LOGGER.info(f"MongoDB: wrote {written} config var(s) to config.env.")
    except Exception as e:
        _LOGGER.warning(f"Could not write config.env: {e}")

# ── Step 5: Install packages ────────────────────────────────────────────────
_do_upgrade = True
if isinstance(UPDATE_PKGS, str):
    _do_upgrade = UPDATE_PKGS.lower() not in ("false", "0", "no")

_LOGGER.info(f"Updating packages (UPDATE_PKGS={_do_upgrade}) ...")

from shutil import which as _which

_venv = environ.get("VIRTUAL_ENV", "").strip()
_venv_pip = path.join(_venv, "bin", "pip") if _venv else ""

if _venv and path.exists(_venv_pip):
    _uflag   = "--upgrade " if _do_upgrade else ""
    _pip_cmd = f"{_venv_pip} install {_uflag}-r requirements.txt -q --no-warn-script-location"
    _LOGGER.info(f"Package installer: venv pip ({_venv_pip})")
else:
    _uv = _which("uv")
    if _uv:
        _uflag   = "-U " if _do_upgrade else ""
        _pip_cmd = f"{_uv} pip install --system {_uflag}-r requirements.txt -q"
        _LOGGER.info(f"Package installer: uv ({_uv})")
    else:
        _pip_bin = _which("pip3") or _which("pip") or "pip3"
        _uflag   = "--upgrade " if _do_upgrade else ""
        _pip_cmd = f"{_pip_bin} install {_uflag}-r requirements.txt -q --no-warn-script-location --break-system-packages"
        _LOGGER.info(f"Package installer: pip ({_pip_bin})")

ret = scall(_pip_cmd, shell=True)
if ret == 0:
    _LOGGER.info("Successfully Updated all the Packages !")
else:
    _LOGGER.warning("Package install had warnings — continuing anyway.")
